name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  # milliseconds: # change this
  #   required: true
  #   description: 'input description here'
  #   default: 'default value if applicable'
  file:
    required: true
    description: '文件入口'
    default: 'default value if applicable'
outputs:
  QR_CODE_BASE64:
    description: 'base64'
runs:
  using: 'node12'
  main: 'dist/index.js'
